development:
  client_id: "251038995973-htec3e86ehg58n7t5mfcenmqrj2qv240.apps.googleusercontent.com"
  client_secret: "KFxKmKe5gVN9C4fjUCCUcSZ2"

production:
  client_id: "251038995973-htec3e86ehg58n7t5mfcenmqrj2qv240.apps.googleusercontent.com"
  client_secret: "KFxKmKe5gVN9C4fjUCCUcSZ2"