development:
  #client_id: "251038995973-htec3e86ehg58n7t5mfcenmqrj2qv240.apps.googleusercontent.com"
  #client_secret: "KFxKmKe5gVN9C4fjUCCUcSZ2"
  client_id: "751699330278-km30eub632rrpqvi0nudg4n3gcd1ov11.apps.googleusercontent.com"
  client_secret: "wQvxSDDRnqUwYIb83BRe9we3"

production:
  client_id: "251038995973-htec3e86ehg58n7t5mfcenmqrj2qv240.apps.googleusercontent.com"
  client_secret: "KFxKmKe5gVN9C4fjUCCUcSZ2"