development:
  api_key: "atYwTpWf3iWvJ4gUEuQwnWoQ8"
  api_secret: "DYjVO3jb2tps9FZlL0MamTH479pev09oArUYbIJPfc673rbQia"

production:
  api_key: "atYwTpWf3iWvJ4gUEuQwnWoQ8"
  api_secret: "DYjVO3jb2tps9FZlL0MamTH479pev09oArUYbIJPfc673rbQia"